# Generated by Django 5.0 on 2024-02-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitalizations", "0006_remove_hospitalization_medical_card"),
        ("medical_cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalcard",
            name="hospitalization",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medical_card",
                to="hospitalizations.hospitalization",
                verbose_name="Медицинская карта",
            ),
        ),
        migrations.AlterField(
            model_name="medicalcard",
            name="diagnosis",
            field=models.ManyToManyField(
                blank=True,
                related_name="medical_cards",
                to="medical_cards.diagnosis",
                verbose_name="Диагнозы",
            ),
        ),
    ]
