# Generated by Django 5.0 on 2024-01-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Имя"
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Фамилия"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Отчество",
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Дата рождения")),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Статус"),
                ),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
                "ordering": ("surname",),
                "indexes": [
                    models.Index(
                        fields=["surname", "name", "patronymic"],
                        name="patients_pa_surname_8ab607_idx",
                    ),
                    models.Index(
                        fields=["time_create"],
                        name="patients_pa_time_cr_6212d5_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("surname", "name", "patronymic", "birthday"),
                name="unique_patient",
            ),
        ),
    ]
