# Generated by Django 5.0 on 2024-01-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="incapacity",
            field=models.BooleanField(
                default=False, verbose_name="Недееспособность"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="registration_address",
            field=models.TextField(
                blank=True, verbose_name="Адрес регистрации"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="residential_address",
            field=models.TextField(
                blank=True, verbose_name="Адрес проживания"
            ),
        ),
    ]
