# Generated by Django 5.0 on 2024-02-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disabilities", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="disability",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hospitalizations",
                to="disabilities.disability",
                verbose_name="Нетрудоспособность",
            ),
        ),
    ]
