# Generated by Django 5.0 on 2024-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "patients",
            "0002_patient_incapacity_patient_registration_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="incapacity",
            field=models.BooleanField(
                choices=[(False, "нет"), (True, "да")],
                default=0,
                verbose_name="Недееспособность",
            ),
        ),
    ]
