# Generated by Django 5.0 on 2024-02-18 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_patient_disability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="disability",
        ),
    ]
