version: "3.3"

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - local

  redisinsight:
    container_name: redis_insight
    image: redislabs/redisinsight:latest
    env_file:
      - crm/.env
    ports:
      - "8001:8001"
    volumes:
      - redisdata:/var/lib/redis/data
    networks:
      - local

  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - crm/.env
    restart: always
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - crm/.env
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - local

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - crm/.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/data
    networks:
      - local

volumes:
  pgdata:
  redisdata:
  rabbitmq:

networks:
  local: