# Generated by Django 5.0 on 2024-02-17 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disability_start_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата начала больничного листа",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
                "ordering": ["disability_start_date"],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(unique=True, verbose_name="Диагноз"),
                ),
                (
                    "icd_code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Код диагноза по МКБ-10",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диагноз",
                "verbose_name_plural": "Диагнозы",
                "ordering": ["diagnosis"],
                "indexes": [
                    models.Index(
                        fields=["icd_code"],
                        name="hospitaliza_icd_cod_4ef705_idx",
                    ),
                    models.Index(
                        fields=["diagnosis"],
                        name="hospitaliza_diagnos_08f72a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DisabilityCommissionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата ВК для ЭВН"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comission_dates",
                        to="hospitalizations.disability",
                        verbose_name="Нетрудоспособные",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дата ВК на ЭВН",
                "verbose_name_plural": "Даты ВК на ЭВН",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Место работы",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Работодатель",
                "verbose_name_plural": "Работодатели",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name"], name="hospitaliza_name_a656d7_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="disability",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disabilities",
                to="hospitalizations.employer",
                verbose_name="Работа",
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Должность"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name"], name="hospitaliza_name_46a68a_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="disability",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disabilities",
                to="hospitalizations.position",
                verbose_name="Должность",
            ),
        ),
        migrations.CreateModel(
            name="Hospitalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата поступления",
                    ),
                ),
                (
                    "leaving_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Дата выписки",
                    ),
                ),
                (
                    "involuntary",
                    models.BooleanField(
                        choices=[(False, "нет"), (True, "да")],
                        default=0,
                        verbose_name="Недобровольная госпитализация",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Заметки"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=15, verbose_name="Номер медицинской карты"
                    ),
                ),
                (
                    "custom_diagnosis",
                    models.TextField(blank=True, verbose_name="Диагноз"),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_cards",
                        to="hospitalizations.diagnosis",
                        verbose_name="Диагноз",
                    ),
                ),
                (
                    "disability",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospitalizations",
                        to="hospitalizations.disability",
                        verbose_name="Нетрудоспособность",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospitalizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лечащий врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalizations",
                        to="patients.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Госпитализация",
                "verbose_name_plural": "Госпитализации",
                "ordering": ["patient__surname"],
                "indexes": [
                    models.Index(
                        fields=["leaving_date"],
                        name="hospitaliza_leaving_3440cd_idx",
                    ),
                    models.Index(
                        fields=["-entry_date"],
                        name="hospitaliza_entry_d_aeeda4_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hospitalization",
            constraint=models.UniqueConstraint(
                fields=("entry_date", "patient"), name="unique_hospitalization"
            ),
        ),
    ]
