# Generated by Django 5.0 on 2024-01-21 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hospitalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата поступления",
                    ),
                ),
                (
                    "leaving_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="Дата выписки",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospitalizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лечащий врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalizations",
                        to="patients.patient",
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "notes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospitalization",
                        to="hospitalizations.note",
                        verbose_name="Заметки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Госпитализация",
                "verbose_name_plural": "Госпитализации",
                "ordering": ["patient__surname"],
                "indexes": [
                    models.Index(
                        fields=["leaving_date"],
                        name="hospitaliza_leaving_3440cd_idx",
                    ),
                    models.Index(
                        fields=["-entry_date"],
                        name="hospitaliza_entry_d_aeeda4_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hospitalization",
            constraint=models.UniqueConstraint(
                fields=("entry_date", "patient"), name="unique_hospitalization"
            ),
        ),
    ]
