# Generated by Django 5.0 on 2024-04-01 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospitalizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disability",
            name="employer",
        ),
        migrations.RemoveField(
            model_name="disability",
            name="position",
        ),
        migrations.RemoveField(
            model_name="disabilitycommissiondate",
            name="job",
        ),
        migrations.RemoveField(
            model_name="hospitalization",
            name="disability",
        ),
        migrations.DeleteModel(
            name="Employer",
        ),
        migrations.DeleteModel(
            name="Position",
        ),
        migrations.DeleteModel(
            name="DisabilityCommissionDate",
        ),
        migrations.DeleteModel(
            name="Disability",
        ),
    ]
