# Generated by Django 5.0 on 2024-01-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospitalizations", "0002_alter_hospitalization_notes_delete_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disability_start_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата начала больничного листа",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
                "ordering": ["disability_start_date"],
            },
        ),
        migrations.AddField(
            model_name="hospitalization",
            name="involuntary",
            field=models.BooleanField(
                default=False, verbose_name="Недобровольная госпитализация"
            ),
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True, unique=True, verbose_name="Диагноз"
                    ),
                ),
                (
                    "icd_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        unique=True,
                        verbose_name="Код диагноза по МКБ-10",
                    ),
                ),
            ],
            options={
                "verbose_name": "Диагноз",
                "verbose_name_plural": "Диагнозы",
                "ordering": ["diagnosis"],
                "indexes": [
                    models.Index(
                        fields=["icd_code"],
                        name="hospitaliza_icd_cod_4ef705_idx",
                    ),
                    models.Index(
                        fields=["diagnosis"],
                        name="hospitaliza_diagnos_08f72a_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="hospitalization",
            name="disability",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hospitalizations",
                to="hospitalizations.disability",
                verbose_name="Нетрудоспособность",
            ),
        ),
        migrations.CreateModel(
            name="DisabilityCommissionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата ВК для ЭВН"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comission_dates",
                        to="hospitalizations.disability",
                        verbose_name="Нетрудоспособные",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дата ВК на ЭВН",
                "verbose_name_plural": "Даты ВК на ЭВН",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Место работы",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Работодатель",
                "verbose_name_plural": "Работодатели",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name"], name="hospitaliza_name_a656d7_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="disability",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disabilities",
                to="hospitalizations.employer",
                verbose_name="Работа",
            ),
        ),
        migrations.CreateModel(
            name="MedicalCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        verbose_name="Номер медицинской карты",
                    ),
                ),
                (
                    "diagnosis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hospitalizations",
                        to="hospitalizations.diagnosis",
                        verbose_name="Диагнозы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинская карта",
                "verbose_name_plural": "Медицинские карты",
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="hospitalization",
            name="medical_card",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hospitalization",
                to="hospitalizations.medicalcard",
                verbose_name="Медицинская карта",
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Должность"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name"], name="hospitaliza_name_46a68a_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="disability",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disabilities",
                to="hospitalizations.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalcard",
            index=models.Index(
                fields=["number"], name="hospitaliza_number_69dd06_idx"
            ),
        ),
    ]
