# Generated by Django 5.0 on 2024-02-13 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospitalizations", "0005_remove_medicalcard_diagnosis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospitalization",
            name="medical_card",
        ),
    ]
