# Generated by Django 5.0 on 2023-12-30 12:59

import easy_thumbnails.fields
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[users.validators.RussianValidator()],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[users.validators.RussianValidator()],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                null=True,
                upload_to=users.validators.UploadToAndRename("users/avatars"),
                validators=[
                    users.validators.ImageMinDimValidator((100, 100)),
                    users.validators.ImageMaxDimValidator((600, 600)),
                    users.validators.ImageSizeValidator(256000),
                ],
                verbose_name="Фотография",
            ),
        ),
    ]
