# Generated by Django 5.0 on 2024-02-18 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("disabilities", "0001_initial"),
        ("patients", "0003_remove_patient_disability"),
    ]

    operations = [
        migrations.AddField(
            model_name="disability",
            name="patient",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disability",
                to="patients.patient",
                verbose_name="Пациент",
            ),
        ),
    ]
